# Upsampling and Downsampling

# 1 Upsampling -  replace is TRUE 
# 2 Downsampling - replace is FALSE because we want to reduce the data, downsampling is not good as we are loosing the data.

In [1]:
import numpy as np
import pandas as pd 

np.random.seed(123)

n_samples = 1000
class_0_ration = 0.9
n_class_0 = int(n_samples * class_0_ration)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [4]:
#create my df with imbalanced dataset

class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0.0, scale=1.0, size=n_class_0),
    'feature2': np.random.normal(loc=5.0, scale=2.0, size=n_class_0),
    'target': np.zeros(n_class_0)
})  

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=2.0, scale=1.0 , size=n_class_1),
    'feature2': np.random.normal(loc=7.0, scale=2.0, size=n_class_1),
    'target': np.ones(n_class_1)
})  

print(class_0, class_1)

     feature1   feature2  target
0   -1.774224   5.571488     0.0
1   -1.201377   5.666559     0.0
2    1.096257   6.063613     0.0
3    0.861037   4.290469     0.0
4   -1.520367   2.758371     0.0
..        ...        ...     ...
895 -0.896718  10.081029     0.0
896  0.812571   4.834587     0.0
897  0.637361   5.889243     0.0
898  0.332712   8.792808     0.0
899  0.258237   5.475161     0.0

[900 rows x 3 columns]     feature1   feature2  target
0  -0.643425   8.143846     1.0
1   1.551009   6.565535     1.0
2   1.641093   7.108636     1.0
3   2.133194   7.311995     1.0
4   1.355758   7.935619     1.0
..       ...        ...     ...
95  2.677156   5.184096     1.0
96  2.963404   3.363911     1.0
97  1.621476   6.754534     1.0
98  3.429559  10.588972     1.0
99  3.532273   6.358981     1.0

[100 rows x 3 columns]

In [10]:
df = pd.concat([class_0, class_1], axis=0).reset_index(drop=True)

In [11]:
df.head()

   feature1  feature2  target
0 -1.774224  5.571488     0.0
1 -1.201377  5.666559     0.0
2  1.096257  6.063613     0.0
3  0.861037  4.290469     0.0
4 -1.520367  2.758371     0.0

In [12]:
df_minority = df[df.target == 1]
df_majority = df[df.target == 0]

In [15]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in /Users/gyanendramohanpatel/Desktop/Data Analytics/venv/lib/python3.13/site-packages (from scikit-learn) (2.3.2)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.16.2-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.2-cp313-cp313-macosx_12_0_arm64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 4.1 MB/s eta 0:00:00a 0:00:01
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading scipy-1.16.2-cp313-cp313-macosx_14_0_arm64.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 8.4 MB/s eta 0:00:00a 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.2 scikit-learn-1.7.2 scipy-1.16.2 threadpoolctl-3.6.0

In [16]:
from sklearn.utils import resample #it extrapolates the minority class, ie it creates new samples from the existing samples by random sampling with replacement

In [17]:
df_minority_upsampled = resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)

In [19]:
df_minority_upsampled.shape

(900, 3)

In [20]:
df.head()

   feature1  feature2  target
0 -1.774224  5.571488     0.0
1 -1.201377  5.666559     0.0
2  1.096257  6.063613     0.0
3  0.861037  4.290469     0.0
4 -1.520367  2.758371     0.0

In [22]:
df_upsampled=pd.concat([df_majority, df_minority_upsampled])
df_upsampled

     feature1  feature2  target
0   -1.774224  5.571488     0.0
1   -1.201377  5.666559     0.0
2    1.096257  6.063613     0.0
3    0.861037  4.290469     0.0
4   -1.520367  2.758371     0.0
..        ...       ...     ...
952  1.766644  6.064449     1.0
965  1.527330  7.364955     1.0
976  2.463277  4.591233     1.0
942  2.930412  5.134705     1.0
974  1.866832  8.446564     1.0

[1800 rows x 3 columns]

In [24]:
df_upsampled['target'].value_counts()

target
0.0    900
1.0    900
Name: count, dtype: int64